#!/usr/bin/env node
require('dotenv').config();

const cli = require('cli');
const Twitter = require('twitter');

const client = new Twitter({
    consumer_key: process.env.TWITTER_API_KEY,
    consumer_secret: process.env.TWITTER_API_SECRET,
    access_token_key: process.env.TWITTER_ACCESS_TOKEN,
    access_token_secret: process.env.TWITTER_ACCESS_TOKEN_SECRET,
});

let colors = {};

client.get('statuses/user_timeline', {
    screen_name: 'everycolorbot',
    count: 1,
    trim_user: true,
    exclude_replies: true,
    include_rts: false
}).then((tweets) => {
    // Retrieve the first Tweet on the timeline so we have it's ID for the next query.
    colors[tweets[0].id_str] = {};
}).then(() => {
    // Loop through the rest of the Tweets now we have an ID start point.
    for (let i = 0; i <= 100; i++) {
        client.get('statuses/user_timeline', {
            screen_name: 'everycolorbot',
            count: 200,
            trim_user: true,
            exclude_replies: true,
            include_rts: false,
            min_id: Object.keys(colors)[0],
            max_id: Object.keys(colors)[Object.keys(colors).length - 1],
        }).then((tweets) => {
            for (const tweet of tweets) {
                colors[tweet.id_str] = {
                    color: tweet.text.split(' ')[0].replace('0x', '#'),
                    interactions: tweet.favorite_count + tweet.retweet_count,
                };
            }
        }).then(() => {
            if (i === 100) {
                console.log(colors, Object.keys(colors).length);
            }
        });
    }
}).catch((error) => {
    console.log(error);
});
